

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://localhost:5433/hotelservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  config:
#    import: optional:configserver:https://localhost:8085
#  profiles:
#    active: service

#  cloud:
#    config:
#      server:
#
#      name: config-server
#      profile: dev
#      enabled: true
#  config:
#    import: configserver:https://localhost:8085




##register the user service application to eurika server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
server:
  port: 8082
