server:
  port: 8082

spring:
  application:
    name: hotel-service
  profiles:
    active: hotel


  datasource:
    url: jdbc:postgresql://localhost:5433/hotelservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



  #config server is used to extract the eurika server configuration to extract from git
  config:
    import: optional:configserver:https://localhost:8085/




##register the user service application to eurika server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#    preferIpAddress: true

