server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update                    # Auto-update the database schema (update, create, none, ...)
    show-sql: true                         # Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: userservice

   #config server is used to extract the eurika server configuration
  config:
    import: optional:configserver:https://localhost:8085/



#register the user service application to eurika server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#    preferIpAddress: true

