server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ratingservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ratingservice


  #config server is used to extract the eurika server configuration
  config:
    import: optional:configserver:https://localhost:8085/

##register the user service application to eurika server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#    preferIpAddress: true
