spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive       #spring mvc found on classpath, which is incompatible with spring cloud gateway to solve this


  #API gateway route
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri:  http://localhost:8082/
          predicates:
            - Path=/api/hotels/**



server:
  port: 9090



#eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka