spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive       #spring mvc found on classpath, which is incompatible with spring cloud gateway to solve this


  #API gateway route
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri:  http://localhost:8082/   # it indicates that the path given in predicates will be redirects to his
          predicates:
            - Path=/api/hotels/**
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/users/**




server:
  port: 9090



#eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka